### ISSUE TITLE
Weird transparency bug

### ISSUE THREAD

**Issue by savaonepunch** [sanidhya711/text-on-gif#15]
This doesnt happen to all GIFs, only on some. I'm not sure what the issue is, i'm sorry if it is some kind of limitation already mentioned. What im doing is turning GIFs into into Jimp images then turning them back into gifs and saving them. Ive tried doing it with no changes to the jimp images and it still happens. This is how it looks like: https://imgur.com/a/IlRYSLG

This doesn't happen with all GIFs, some are completely fine.

**Comment by sanidhya711** [comment]
Hi, I also experienced this issue when i was building this library. So this is happening because some gifs store color data only in the first frame and that is used again and again. You should check out what "cumulative" gifs are. I know the answer is not detailed at all but you should look up what cumulative gifs are and that should help
