### ISSUE TITLE
How to add text at multiple places?

### ISSUE THREAD

**Issue by Spartanets174** [sanidhya711/text-on-gif#16]
How can I add 2 captions for one GIF? I just cant understand how to do it. 
If you don't mind, then write to me here, pls: quietl2004@gmail.com

**Comment by sanidhya711** [comment]
Hi. To have two captions on one gif follow these steps. (i know this is kinda slow and this option should be built in but since i dont have time to work on this feature right now, make do with this solution)

**TextOnGif constructor accepts a gif buffer too so you can => write on a gif => get it as buffer => use that buffer to create a new TextOnGif object => write on the new object => now you have text at multiple places**

**Comment by Spartanets174** [comment]
Thanks man, i will try it!  пятница, 03 февраля 2023, 04:31PM +05:00 от sanidhya711  ***@***.*** :

**Comment by sanidhya711** [comment]
The newer version has the "retain" property which changes the TextOnGif object to return the gif with cumulative text on all subsequent obj.textOnGif() calls
