### ISSUE TITLE
Support for multiple text

### ISSUE THREAD

**Issue by ExordiumX** [sanidhya711/text-on-gif#7]
Add support for adding text at multiple places on a gif.

**Comment by sanidhya711** [comment]
Hi, that would a a awesome feature. It never crossed my mind since for my use case something this complex wasn't needed but would definitely add this feature soon 👍

**Comment by metadanc** [comment]
how close are we to this? hoping to leverage this :)

**Comment by sanidhya711** [comment]
> how close are we to this? hoping to leverage this :) 

Well havent started work on it yet, i did think about how I want to implement this but never really settled on anything. I would try to add this feature soon(maybe today or maybe next week/month)

**Comment by metadanc** [comment]
Sounds good! Just a thought: might be good as a first pass to positionally fix a top text and a bottom text (like a meme generator would)

**Comment by sanidhya711** [comment]
Sorry im not really sure what you mean. For now you can try to save the gif after writing once and then write on it again(not really efficient but will work) because im actually kind of busy these days and not sure if i'll be able to work on it soon because final exams are coming up 😞. Also if you could try looking at the source code once and see if you could add this functionality then it would be awesome( tbh the library is very very simple so i dont think it should be too hard )

**Comment by sanidhya711** [comment]
TextOnGif constructor accepts a gif buffer too so you can write on a gif => get it as buffer => use that buffer to create a new TextOnGif object => write on the new object => now you have text at multiple places
